#!/bin/bash
# Script hướng dẫn tạo Alchemy key mới và cấu hình

echo "=== HƯỚNG DẪN TẠO ALCHEMY KEY MỚI ==="
echo ""
echo "1. Mở trình duyệt: https://dashboard.alchemy.com/"
echo "2. Đăng nhập hoặc tạo account mới (miễn phí)"
echo "3. Click '+ Create new app'"
echo "4. Điền thông tin:"
echo "   - Name: Music Copyright Sepolia 2"
echo "   - Chain: Ethereum"
echo "   - Network: Sepolia"
echo "5. Click 'Create app'"
echo "6. Click vào app vừa tạo"
echo "7. Click 'API Key' button"
echo "8. Copy HTTPS URL (dạng: https://eth-sepolia.g.alchemy.com/v2/NEW_KEY)"
echo ""
echo "=== CẬP NHẬT KEY ==="
echo ""
echo "File 1: frontend/.env"
echo "Sửa dòng:"
echo "VITE_SEPOLIA_RPC=https://eth-sepolia.g.alchemy.com/v2/NEW_KEY_HERE"
echo ""
echo "File 2: backend/.env"
echo "Sửa dòng:"
echo "SEPOLIA_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/NEW_KEY_HERE"
echo ""
echo "=== CẬP NHẬT METAMASK ==="
echo ""
echo "1. MetaMask → Settings → Networks → Sepolia test network"
echo "2. Sửa RPC URL thành URL mới với NEW_KEY"
echo "3. Save"
echo "4. Restart dev server: npm run dev"
echo "5. Reload trang web"
echo ""
echo "=== HOẶC DÙNG RPC KHÁC (TẠM THỜI) ==="
echo ""
echo "Infura public (có thể chậm):"
echo "https://ethereum-sepolia.publicnode.com"
echo ""
echo "Hoặc đăng ký Infura miễn phí:"
echo "https://www.infura.io/"
echo ""
